# Generated by Django 3.1.3 on 2021-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210302_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateandtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
