# Generated by Django 3.1.3 on 2021-03-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210302_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dateandtime',
            new_name='date',
        ),
    ]
